# Generated by Django 4.2 on 2025-08-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('audio_url', models.URLField(blank=True)),
                ('spotify_id', models.CharField(blank=True, max_length=128)),
                ('official_link', models.URLField(blank=True)),
            ],
        ),
    ]
