# Generated by Django 4.2 on 2025-08-13 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={},
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_type',
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='result_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
